services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
